apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.1.0
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: flask-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: This operator will deploy flask application to the cluster.
  displayName: Flask Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - flask
  - operator
  links:
  - name: Flask Operator
    url: https://flask-operator.domain
  maintainers:
  - email: edge@us.ibm.com
    name: IBM-Edge
  maturity: alpha
  provider:
    name: IBM Edge
  version: 0.0.0
