apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "example.com/v1alpha1",
          "kind": "Flask",
          "metadata": {
            "name": "flask-sample"
          },
          "spec": {
            "flask": {
              "image": "quay.io/rhm_samples/flask-server:v0.0.1",
              "imagePullSecrets": [],
              "replicaCount": 1,
              "service": {
                "port": 5000,
                "type": "ClusterIP"
              }
            },
            "vue": {
              "image": "quay.io/rhm_samples/flask-vue-client:v0.0.1",
              "imagePullSecrets": [],
              "replicaCount": 1,
              "service": {
                "port": 8080,
                "type": "ClusterIP"
              }
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: Networking
    description: A brief description about this Flask Operator
    containerImage: quay.io/ritushreepurkait/flask-operator-2:v0.0.1
    createdAt: 2020-10-29T12:59:59Z
    support: IBM Edge
    repository: https://github.com/rhm-samples/helm-charts
    operators.operatorframework.io/builder: operator-sdk-v1.1.0
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: flask-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Flask
      name: flasks.example.com
      version: v1alpha1
      displayName: Flask
      description: Deployment of Flask instance
  description: This operator will deploy flask application to the cluster.
  displayName: Flask Operator
  icon:
  - base64data: ""
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - anyuid
          resources:
          - securitycontextconstraints
          verbs:
          - use
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          - secrets/finalizers
          - pods
          - pods/finalizers
          - pods/exec
          - pods/log
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - persistentvolumes
          - persistentvolumeclaims/finalizers
          - persistentvolumes/finalizers
          - nodes
          - events
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          - deployments/finalizers
          - replicasets/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - example.com
          resources:
          - flasks
          - flasks/status
          - flasks/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          - prometheuses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - batch
          resources:
          - jobs
          - cronjobs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: flask-operator
      deployments:
      - name: flask-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: flask-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: flask-operator
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.6.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                - --leader-election-id=flask-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: flask-operator
                - name: RELATED_IMAGE_FLASK
                  value: quay.io/rhm_samples/flask-server:v0.0.1
                - name: RELATED_IMAGE_VUE
                  value: quay.io/rhm_samples/flask-vue-client:v0.0.1
                image: quay.io/ritushreepurkait/flask-operator-2:v0.0.1
                imagePullPolicy: Always
                name: manager
                resources: {}
              serviceAccountName: flask-operator
              terminationGracePeriodSeconds: 10       
        serviceAccountName: flask-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - flask
  - operator
  links:
  - name: Flask Operator
    url: https://flask-operator.domain
  maintainers:
  - email: edge@us.ibm.com
    name: IBM-Edge
  maturity: alpha
  provider:
    name: IBM Edge
  version: 0.0.1
